from __future__ import annotations

from locallens.schemas import CityRecord
from locallens.utils import slugify


def city(
    name: str,
    region: str,
    latitude: float,
    longitude: float,
    *,
    radius_km: float = 12.0,
    kind: str = "city",
    aliases: list[str] | None = None,
    wikivoyage_page: str = "",
    wikipedia_page: str = "",
    official_url: str = "",
    reddit_subreddits: list[str] | None = None,
    curated_urls: list[str] | None = None,
) -> CityRecord:
    return CityRecord(
        name=name,
        slug=slugify(name),
        region=region,
        latitude=latitude,
        longitude=longitude,
        radius_km=radius_km,
        kind=kind,
        aliases=aliases or [],
        wikivoyage_page=wikivoyage_page or name,
        wikipedia_page=wikipedia_page or name,
        official_url=official_url,
        reddit_subreddits=reddit_subreddits or [],
        curated_urls=curated_urls or [],
    )


CITY_CATALOG: list[CityRecord] = [
    city(
        "San Francisco",
        "California, USA",
        37.7749,
        -122.4194,
        aliases=["sf"],
        official_url="https://www.sftravel.com/",
        reddit_subreddits=["AskSF", "sanfrancisco"],
    ),
    city(
        "San Jose",
        "California, USA",
        37.3382,
        -121.8863,
        aliases=["sj", "silicon valley"],
        wikivoyage_page="San Jose (California)",
        wikipedia_page="San Jose, California",
        official_url="https://www.sanjose.org/",
        reddit_subreddits=["SanJose"],
    ),
    city(
        "Los Angeles",
        "California, USA",
        34.0522,
        -118.2437,
        aliases=["la"],
        official_url="https://www.discoverlosangeles.com/",
        reddit_subreddits=["AskLosAngeles", "LosAngeles"],
    ),
    city(
        "Seattle",
        "Washington, USA",
        47.6062,
        -122.3321,
        official_url="https://visitseattle.org/",
        reddit_subreddits=["Seattle"],
    ),
    city(
        "Las Vegas",
        "Nevada, USA",
        36.1699,
        -115.1398,
        official_url="https://www.visitlasvegas.com/",
        reddit_subreddits=["vegaslocals", "LasVegas"],
    ),
    city(
        "Denver",
        "Colorado, USA",
        39.7392,
        -104.9903,
        official_url="https://www.denver.org/",
        reddit_subreddits=["Denver"],
    ),
    city(
        "San Diego",
        "California, USA",
        32.7157,
        -117.1611,
        official_url="https://www.sandiego.org/",
        reddit_subreddits=["asksandiego", "sandiego"],
    ),
    city(
        "Austin",
        "Texas, USA",
        30.2672,
        -97.7431,
        official_url="https://www.austintexas.org/",
        reddit_subreddits=["Austin"],
    ),
    city(
        "New Orleans",
        "Louisiana, USA",
        29.9511,
        -90.0715,
        official_url="https://www.neworleans.com/",
        reddit_subreddits=["AskNOLA", "NewOrleans"],
    ),
    city(
        "Miami",
        "Florida, USA",
        25.7617,
        -80.1918,
        official_url="https://www.miamiandbeaches.com/",
        reddit_subreddits=["Miami"],
    ),
    city(
        "Washington, DC",
        "District of Columbia, USA",
        38.9072,
        -77.0369,
        aliases=["dc", "washington dc"],
        official_url="https://washington.org/",
        reddit_subreddits=["washingtondc"],
    ),
    city(
        "Nashville",
        "Tennessee, USA",
        36.1627,
        -86.7816,
        official_url="https://www.visitmusiccity.com/",
        reddit_subreddits=["Nashville"],
    ),
    city(
        "Chicago",
        "Illinois, USA",
        41.8781,
        -87.6298,
        official_url="https://www.choosechicago.com/",
        reddit_subreddits=["AskChicago", "chicago"],
    ),
    city(
        "Boston",
        "Massachusetts, USA",
        42.3601,
        -71.0589,
        official_url="https://www.meetboston.com/",
        reddit_subreddits=["boston"],
    ),
    city(
        "New York City",
        "New York, USA",
        40.7128,
        -74.0060,
        aliases=["nyc", "new york"],
        official_url="https://www.nycgo.com/",
        reddit_subreddits=["AskNYC"],
    ),
    city(
        "Portland",
        "Oregon, USA",
        45.5152,
        -122.6784,
        aliases=["pdx"],
        official_url="https://www.travelportland.com/",
        reddit_subreddits=["askportland", "Portland"],
    ),
    city(
        "Philadelphia",
        "Pennsylvania, USA",
        39.9526,
        -75.1652,
        aliases=["philly"],
        official_url="https://www.visitphilly.com/",
        reddit_subreddits=["philadelphia"],
    ),
    city(
        "Atlanta",
        "Georgia, USA",
        33.7490,
        -84.3880,
        aliases=["atl"],
        official_url="https://discoveratlanta.com/",
        reddit_subreddits=["Atlanta"],
    ),
    city(
        "Salt Lake City",
        "Utah, USA",
        40.7608,
        -111.8910,
        aliases=["slc"],
        official_url="https://www.visitsaltlake.com/",
        reddit_subreddits=["SaltLakeCity", "SLC"],
    ),
    city(
        "Orlando",
        "Florida, USA",
        28.5383,
        -81.3792,
        official_url="https://www.visitorlando.com/",
        reddit_subreddits=["orlando"],
    ),
    city(
        "Phoenix",
        "Arizona, USA",
        33.4484,
        -112.0740,
        official_url="https://www.visitphoenix.com/",
        reddit_subreddits=["phoenix"],
    ),
    city(
        "Honolulu",
        "Hawaii, USA",
        21.3069,
        -157.8583,
        official_url="https://www.gohawaii.com/islands/oahu",
        reddit_subreddits=["Honolulu", "VisitingHawaii"],
    ),
    city(
        "Yosemite National Park",
        "California, USA",
        37.8651,
        -119.5383,
        radius_km=18.0,
        kind="park",
        official_url="https://www.nps.gov/yose/index.htm",
        reddit_subreddits=["Yosemite"],
    ),
    city(
        "Grand Canyon National Park",
        "Arizona, USA",
        36.2679,
        -112.3535,
        radius_km=20.0,
        kind="park",
        official_url="https://www.nps.gov/grca/index.htm",
        reddit_subreddits=["grandcanyon"],
    ),
]


CITY_BY_NAME = {record.name: record for record in CITY_CATALOG}
